[package]
name = "sign-request"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
rand = "0.8.4"
reqwest = "0.11"
tokio = { version = "1.17", features = ["full"] }
truelayer-signing = "0.2"
uuid = { version = "1", features = ["v4"] }
